version: '3.0'

services:
  main:
    container_name: poll-bot
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001
    command: npm run start
    environment:
      MONGO_URI: "mongodb://mongodb:27017/pollbot"
    depends_on:
      - mongodb
    restart: always
  mongodb:
    image: mongo:5.0.2
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
